# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iTMknPd4_UPGP9sofxdiYWMtgpV-ePrr
"""

import pandas as pd

user = pd.read_excel("/content/sample_data/ASSIGMENT 2 DATA SAMPLE.xlsx")

user

user.info()

#Display the decription of the sample dataset
user.describe()

#display first headline
user.head()